### ISSUE TITLE
Active participation from committee clause

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/constitution#12]
Members that do not attend x consecutive meetings should be booted off the committee.

**Comment by KitB** [comment]
Can I still send Craig in my stead?

**Comment by himmelmaus** [comment]
This could be dangerous because it could lead to the society becoming defunct, a better clause may be that after a member does not attend x consecutive meetings the rest of the committee votes on whether or not to call an EGM to replace their position - with the replacement effective soon after the EGM.

**Comment by qaisjp** [comment]
society can only be defunct if there is a lack of exec. the committee is generally free to appoint any member to any committee position 

Also, *attend x consecutive meetings without sending apologies

**Comment by himmelmaus** [comment]
I think apologies is too wide, put it to a vote of the committee as to whether the reason for missing them is legitimate

**Comment by qaisjp** [comment]
Apologies is a real thing not a "oh i'm sorry", it's a formal email sent to a secretary when they cannot make a meeting

**Comment by himmelmaus** [comment]
yes I know what you mean, but if somebody repeatedly doesn't show up because they can't be bothered and don't have a legitimate reason to have missed the meeting then that would be fine with this phrasing if they sent an email to the secretary to apologise, it's too ambiguous imo.

**Comment by qaisjp** [comment]
FYI my suggestion was not to 'automatically' boot someone off the committee, it was to put it in stone that if someone does not attend committee meetings then they are at risk of being kicked off.

It would make it a responsibility of office bearers to attend committee meetings, and if they don't attend three consecutive committee meetings, then it would be _up for discussion_ (this is my original intention, and I think this covers your concern, @findoslice?).

I'm not in favour of including "directly go to EGM" because whilst democracy can be fun, you want to dedicate STMUs to talks, rather than losing a slot to an EGM.

Far too many times have we had people simply ignore committee meetings.

I was looking for wording similar to [Article 3, Paragraph A](https://gutechsoc.com/files/constitution2017.pdf), something like this:

>  A member’s position on the committee shall be taken into discussion at
a committee meeting if a member is absent for two consecutive committee meetings, one AGM or one EGM without prior approval of the President or Secretary.

What do you think about that?

**Comment by himmelmaus** [comment]
That would be fine imo, I think maybe slightly more strong language on what "taken into discussion" actually means but other than that I think that meets all concerns. Also changing it from "prior approval "to just "approval" may be a good idea because things can come up at short notice.
