### ISSUE TITLE
RON should be available for all positions

### ISSUE THREAD

**Issue by veniversum** [compsoc-edinburgh/constitution#2]
Seems like EUSA requires that RON be an option for all votes, including those for President, Secretary and Treasurer. 

https://www.eusa.ed.ac.uk/pageassets/activities/societies/runasociety/Elections-and-AGMs(2).pdf

**Comment by AngusP** [comment]
Unless there's a contradiction elsewhere, https://github.com/compsoc-edinburgh/constitution/blob/master/compsoc-constitution.tex#L310 means that RON would always e called including for the executive positions

**Comment by veniversum** [comment]
https://github.com/compsoc-edinburgh/constitution/blob/master/compsoc-constitution.tex#L313-L315 says that RON will not be available for the positions of President, Secretary and Treasurer.

**Comment by AngusP** [comment]
Whups, maybe I should have read a bit further... Yep, RON should be available for all roles
