### ISSUE TITLE
Link to EUSA's copy of the constitution in the releases section is broken.

### ISSUE THREAD

**Issue by ettolrach** [compsoc-edinburgh/constitution#30]
In the releases section, [specifically the latest release at the time of writing (2018-03-22)](https://github.com/compsoc-edinburgh/constitution/releases/tag/v2018-03-22), there is a link to the EUSA website for their copy of the constitution. However, this link is broken. Neither can I find it anyway currently hosted on the EUSA website; they most likely do not host constitutions of their societies any more? At least it's not present on the [Comp Soc EUSA page](https://www.eusa.ed.ac.uk/activities/view/compsoc).

**Comment by tcmal** [comment]
Yeah i guess they don't host it anymore, have removed the link.
